#!/usr/bin/php
<?php

namespace CspRuler;

class Runner
{
    private $tests;
    private $testsPath = 'tests/tests.php';

    public function run()
    {
        $this->loadTests();
        $this->beginTests();
    }

    private function printLine(string $message)
    {
        echo $message . PHP_EOL;
    }

    private function loadTests()
    {
        if (!file_exists($this->testsPath)) {
            $this->printLine('Tests file does not exist.');
            $this->printLine('Please run "cp tests/tests.php.template tests/tests.php" and add your own tests');
            exit(1);
        }

        $this->tests = require_once($this->testsPath);

        if (!is_array($this->tests) || emtpy($this->tests)) {
            $this->printLine('Tests file does not contain an array.');
            exit(1);
        }
    }

    private function beginTests()
    {

    }
}

$runner = new \CspRuler\Runner();
$runner->run();
